---
title: "P4DS_LBB"
author: "Reza Dwi Utomo @utomoreza"
date: "23/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# Dataset

## Methodology Used

[methodology and metadata](https://www.glassdoor.com/research/app/uploads/sites/2/2019/04/Methodology-Glassdoor-Job-Market-Report-2-2.pdf)

# Preparation

## Load Necessary Packages

```{r}
library('readxl')
library('rvest')
library('lubridate')
library('zoo')
library('openxlsx')
```

```{r}
get_xls_file_from_html <- function() {
    dataurl <- "https://www.glassdoor.com/research/job-market-report-historical/"
    page <- read_html(dataurl)
    
    excels1 <- grep("\\.xlsx", html_nodes(page, "a"), value = T)
    excels2 <- gsub(".*href=\"", "", excels1)
    excels <- gsub("xlsx.*", "xlsx", excels2)
    excels_path <- as.character(sapply(excels,
                                       FUN = substr,
                                       start = 64,
                                       stop = max(sapply(excels, nchar))))
    excels_path1_31 <- gsub(".*data-", "", excels_path[1:31])
    excels_path[32] <- "2017-05.xlsx"
    excels_path[33] <- "2017-04.xlsx"
    excels_path[34] <- "2017-03.xlsx"
    excels_path[35] <- "2017-02.xlsx"
    excels_path[36] <- "2017-01.xlsx"
    excels_path[37] <- "2016-12.xlsx"
    excels_path[38] <- "2016-11.xlsx"
    excels_path[39] <- "2016-10.xlsx"
    
    excels_path <- c(excels_path1_31, excels_path[32:39])
    
    destination <- paste("./datasets/", excels_path, sep = "")
    
    #file extraction
    mapply(function(x, y) download.file(x, y, mode="wb"), x = excels, y = destination)
}
```

```{r}
load("filespath.RData")

if (!file.exists(filespath)) {
        get_xls_file_from_html
    }

# check_if_fileexist <- function(){
#     if (!file.exists(filespath)) {
#         get_xls_file_from_html
#     }
# }

# mapply(check_if_fileexist)
```

```{r}
source("select_files_to_read.R")
# select_files_to_read("Dec", 2019)

myexport <- function(...) {
    arg.list <- list(...)
    names <- all.names(match.call())[-1]
    for (i in seq_along(names)) assign(names[i],arg.list[[i]],.GlobalEnv)
}

loadMultipleFiles <- function(nmonth = c("Dec"), nyear = c(2019)) {
    files_list1 <- list()
    year <- 1:length(nyear)
    month <- 1:length(nmonth)
    totalIterate <<- length(nmonth) * length(nyear)

    for (i in year) {
        if (length(year) == 1) {
            for (j in month) {
            select_files_to_read(nmonth[j], nyear)
            files_list1[[j]] <- tempfilename
            names(files_list1)[j] <- xlsname
            }
            break
        }
        for (j in month) {
            # browser()
            select_files_to_read(nmonth[j], nyear[i])
            files_list1[[j]] <- tempfilename
            names(files_list1)[j] <- xlsname
            # browser()
        }
        # browser()
    }
    files_list <<- files_list1
}
```

```{r}
loadMultipleFiles(nmonth = c("Dec","Nov","Oct","Sep","Aug","Jul","Jun","May","Apr","Mar","Feb","Jan"))

for (k in 1:totalIterate) {
    # browser()
    assign(names(files_list)[k], as.data.frame(files_list[[k]]))
    # browser()
}
rm(files_list, tempfilename)
```

## Combine months DFs into 1 DF (year)
```{r}
# totalDF <- ls(pattern = "2019")

year2019 <- rbind(Apr2019, Aug2019, Dec2019, Feb2019, Jan2019, Jul2019, Jun2019, Mar2019, May2019, Nov2019, Oct2019, Sep2019)

# write.xlsx(year2019, "./datasets/year2019.xlsx")
```

Yeah! Finally, we've got our prepared data! Let's move on to clean the data.

# Data Cleaning

```{r}
str(year2019)
```

```{r}
colnames(year2019) <- c("Metro", "Dimension_Type", "Year_Month", "Dimension", "Measure", "Value", "YoY")

# unique(year2019$Metro) # Change to Factor
# unique(year2019$Dimension_Type) # Change to Factor
# unique(year2019$Measure) # Change to Factor
# unique(year2019$Dimension) # Keep the data type
# 
# year2019$Metro <- as.factor(year2019$Metro)
# year2019$Dimension_Type <- as.factor(year2019$Dimension_Type)
# year2019$Measure <- as.factor(year2019$Measure)
# year2019$Year_Month <- as.Date(sapply(year2019$Year_Month, as.yearmon))
# for (i in nrow(year2019)) {
#     year2019$Year_Month[i] <- as.Date(as.yearmon(year2019$Year_Month[i]))
# }
# 
# year(year2019$Month)
```

# Data Transformation

# Plotting

# Inference

# Conclusions
